version: '3'
services:
  pgdb:
    image: "postgres:11"
    container_name: "pgdb"
    environment:
      - POSTGRES_DB=backend_db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pwd123
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
    - "54322:5432"
    volumes:
     - /Users/mac/Documents/docker-volumes:/var/lib/postgresql/data
